# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('compressed-sensing-example', ['compressed-sensing'])
    obj.source = 'compressed-sensing-example.cc'
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/KL1p")
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/KLab")
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/KSci")
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/Armadillo")
    #obj.env.append_value("CXXFLAGS", "-Wno-error")
    obj.env.append_value("LINKFLAGS", "-L../src/compressed-sensing/lib/")
    obj.env.append_value("LIB",["dl","KLab64_d"])

    obj = bld.create_ns3_program('node-buffer-example', ['compressed-sensing'])
    obj.source = 'node-buffer-example.cc'
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/KL1p")
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/KLab")
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/KSci")
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/Armadillo")
    #obj.env.append_value("CXXFLAGS", "-Wno-error")
    obj.env.append_value("LINKFLAGS", "-L../src/compressed-sensing/lib/")
    obj.env.append_value("LIB",["dl","KLab64_d"])

    obj = bld.create_ns3_program('node-buffer-meta-example', ['compressed-sensing'])
    obj.source = 'node-buffer-meta-example.cc'
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/KL1p")
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/KLab")
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/KSci")
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/Armadillo")
    #obj.env.append_value("CXXFLAGS", "-Wno-error")
    obj.env.append_value("LINKFLAGS", "-L../src/compressed-sensing/lib/")
    obj.env.append_value("LIB",["dl","KLab64_d"])

    obj = bld.create_ns3_program('random-matrix-example', ['compressed-sensing'])
    obj.source = 'random-matrix-example.cc'
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/KL1p")
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/KLab")
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/KSci")
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/Armadillo")
    #obj.env.append_value("CXXFLAGS", "-Wno-error")
    obj.env.append_value("LINKFLAGS", "-L../src/compressed-sensing/lib/")
    obj.env.append_value("LIB",["dl","KLab64_d"])

    obj = bld.create_ns3_program('omp-reconst-example', ['compressed-sensing'])
    obj.source = 'omp-reconst-example.cc'
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/KL1p")
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/KLab")
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/KSci")
    obj.env.append_value("CXXFLAGS", "-isystem../src/compressed-sensing/lib/include/Armadillo")
    #obj.env.append_value("CXXFLAGS", "-Wno-error")
    obj.env.append_value("LINKFLAGS", "-L../src/compressed-sensing/lib/")
    obj.env.append_value("LIB",["dl","KLab64_d"])
